# Generated by Django 3.0.2 on 2020-03-04 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecoli_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_ecoli_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GRCZ11_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_GRCZ11_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='hg38_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_hg38_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='mm10_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_mm10_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='rice_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_rice_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TAIR10_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_TAIR10_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WBcel235_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_WBcel235_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='yeast_Gene',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
            ],
            options={
                'db_table': 'RNAProb_yeast_gene',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='yeast_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.yeast_Gene')),
            ],
            options={
                'db_table': 'RNAProb_yeast_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='yeast_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.yeast_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_yeast_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='yeast_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.yeast_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_yeast_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WBcel235_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.WBcel235_Gene')),
            ],
            options={
                'db_table': 'RNAProb_WBcel235_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WBcel235_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.WBcel235_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_WBcel235_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WBcel235_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.WBcel235_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_WBcel235_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TAIR10_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.TAIR10_Gene')),
            ],
            options={
                'db_table': 'RNAProb_TAIR10_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TAIR10_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.TAIR10_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_TAIR10_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TAIR10_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.TAIR10_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_TAIR10_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='rice_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.rice_Gene')),
            ],
            options={
                'db_table': 'RNAProb_rice_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='rice_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.rice_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_rice_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='rice_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.rice_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_rice_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='mm10_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.mm10_Gene')),
            ],
            options={
                'db_table': 'RNAProb_mm10_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='mm10_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.mm10_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_mm10_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='mm10_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.mm10_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_mm10_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='hg38_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hg38_Gene')),
            ],
            options={
                'db_table': 'RNAProb_hg38_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='hg38_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hg38_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_hg38_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='hg38_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hg38_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_hg38_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GRCZ11_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.GRCZ11_Gene')),
            ],
            options={
                'db_table': 'RNAProb_GRCZ11_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GRCZ11_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.GRCZ11_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_GRCZ11_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GRCZ11_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.GRCZ11_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_GRCZ11_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ecoli_Transcript',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=30)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('biotype', models.CharField(max_length=35)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.ecoli_Gene')),
            ],
            options={
                'db_table': 'RNAProb_ecoli_transcript',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ecoli_Exon',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.ecoli_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_ecoli_exon',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ecoli_CDS',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chrId', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.BooleanField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.ecoli_Transcript')),
            ],
            options={
                'db_table': 'RNAProb_ecoli_cds',
            },
            managers=[
                ('RM', django.db.models.manager.Manager()),
            ],
        ),
    ]
