# Generated by Django 3.0.2 on 2020-03-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BwData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=35)),
                ('journal', models.CharField(max_length=40)),
                ('publishYear', models.CharField(max_length=4)),
                ('doi', models.CharField(max_length=30)),
                ('firstAuthor', models.CharField(max_length=25)),
                ('commuAuthor', models.CharField(max_length=25)),
                ('dataProduction', models.CharField(max_length=25)),
                ('reagent', models.CharField(max_length=20)),
                ('techName', models.CharField(blank=True, max_length=25)),
                ('expCondition', models.CharField(blank=True, max_length=200)),
                ('strand', models.CharField(max_length=1)),
                ('filePath', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'RNAProb_BwData',
            },
        ),
    ]
